### ISSUE TITLE
Getting ErrorCode 403 on all requests

### ISSUE THREAD

**Issue by GilitikoWiz** [pancak3lullz/SECurityTr8Ker#2]
Apparently the SEC is now limiting access with automated tools, so all requests from the current script receive a 403 response with this content: 
```
To allow for equitable access to all users, SEC reserves the right to limit requests originating from undeclared automated tools. Your request has been identified as part of a network of automated tools outside of the acceptable policy and will be managed until action is taken to declare your traffic.
```

The fix that worked for me is simply replacing the User-Agent in the request to one that contains a company name and email address per the SEC's instructions

```Test Company {my_email}@gmail.com```

https://www.sec.gov/about/webmaster-frequently-asked-questions#developers

Maybe this should be documented in the Readme? and added as a command-line argument.

![image](https://github.com/user-attachments/assets/0a7369bc-ab23-46aa-ada8-ebe710861e70)

**Comment by pancak3lullz** [comment]
This is not new. Yes, you need to change the User-Agent information. The script I provide in this repo is a template.
